# Reference:
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: "Install Racket"
description: "Install Racket for Linux, macOS, and Windows"

inputs:
  version:
    description: The version of Racket to install, e.g. 8.11 or 'stable' or 'pre-release'
    required: true
  variant:
    description: "'CS' for Chez Scheme or 'BC' for Racket Before Chez"
    required: false
    default: CS
  distribution:
    description: "'full' or 'minimal'"
    required: true
    default: full
  cached:
    description: "Whether to try to cache the installation"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: set up environment
      shell: bash
      run: |
        if [[ ${{runner.arch}} = 'X64' ]]; then
          racket_arch="x64"
        elif [[ ${{runner.arch}} = 'ARM64' ]]; then
          racket_arch="arm64"
        elif [[ ${{runner.arch}} = 'X86' ]]; then
          racket_arch="x86"
        elif [[ ${{runner.arch}} = 'ARM' ]]; then
          racket_arch="arm32"
        else
          echo "Unsupported architecture: ${{runner.arch}}"
          exit 1
        fi
        echo "racket_arch=$racket_arch" >> $GITHUB_ENV

    - name: cache Racket installation (Linux)
      id: cache-linux
      # caching doesn't work here without extra work, due to https://github.com/actions/cache/issues/133
      if: false && inputs.cached == 'true' && runner.os == 'Linux'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: |
          /usr/*/racket
          ~/.local/*/racket
        key: ${{runner.os}}-racket-${{inputs.version}}-${{inputs.variant}}-${{inputs.distribution}}

    - name: cache Racket installation (macOS)
      id: cache-macos
      if: inputs.cached == 'true' && runner.os == 'macOS'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: |
          /Applications/Racket
          ~/Library/Racket
        key: ${{runner.os}}-racket-${{inputs.version}}-${{inputs.variant}}-${{inputs.distribution}}

    - name: cache Racket installation (Windows)
      id: cache-windows
      if: inputs.cached == 'true' && runner.os == 'Windows'
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: |
          C:\Program Files\Racket\
          C:\Users\runneradmin\AppData\Roaming\Racket\
        key: ${{runner.os}}-racket-${{inputs.version}}-${{inputs.variant}}-${{inputs.distribution}}

    - name: add Racket to path (Linux)
      if: steps.cache-linux.outputs.cache-hit == 'true'
      shell: bash
      run: echo "/usr/racket/bin" >> $GITHUB_PATH

    - name: add Racket to path (macOS)
      if: steps.cache-macos.outputs.cache-hit == 'true'
      shell: bash
      run: echo "/Applications/Racket/bin" >> $GITHUB_PATH

    - name: add Racket to path (Windows)
      if: steps.cache-windows.outputs.cache-hit == 'true'
      shell: bash
      run: echo "/c/Program Files/Racket" >> $GITHUB_PATH

    - uses: Bogdanp/setup-racket@0094a9d8bd157633293a2210f373bb542687fa6d # v1.11
      if: |
        ${{inputs.cached}} != 'true' || \
        (steps.cache-linux.outputs.cache-hit != 'true' && \
         steps.cache-macos.outputs.cache-hit != 'true' && \
         steps.cache-windows.outputs.cache-hit != 'true')
      with:
        architecture: ${{env.racket_arch}}
        distribution: ${{inputs.distribution}}
        variant: ${{inputs.variant}}
        version: ${{inputs.version}}
